const episodeDescriptions = {
    'S01E01':'A strangely eccentric genius scientist and inventor moves into the home of his daughter and her family and begins to strongly influence his young grandson.',
    'S01E02':'Rick helps Jerry out with the dog.',
    'S01E03':'It\'s Christmas. Rick shrinks Morty, injecting him into a homeless man to save Anatomy Park. Jerry tries to have a Christmas free of electronic devices, but regrets his decision when his parents introduce him to their new friend.',
    'S01E04':'Rick and Morty try to get to the bottom of a mystery.',
    'S01E05':'Rick provides the family with a solution to their problems, freeing him up to go on an adventure led by Morty.',
    'S01E06':'After Rick gives Morty a love potion for a school dance, things quickly spiral out of control when the serum splices with the flu - causing it to spread. Rick and Morty scramble to cure the crisis, making matters worse in the process.',
    'S01E07':'Morty becomes a father to an alien baby, while Rick and Summer get trapped in a dangerous dimension.',
    'S01E08':'Rick hooks up the family\'s TV with interdimensional cable, allowing them to watch infinite TV from across the multiverse.',
    'S01E09':'Summer gets a job at a pawn shop owned by the devil. Jerry helps Morty with his science fair project.',
    'S01E10':'Rick, falsely blamed for Murder by the council of Ricks, begins a cross-dimensional pursuit with the authorities while attempting to prove his innocence.',
    'S01E11':'Beth and Jerry head for an iceberg of a date leaving Rick in charge. Morty doesn\'t get to go on any more adventures if the house isn\'t in the same condition when they get back.',
    'S02E01':'Having restarted time, Rick, Morty and Summer are in a quantum-uncertain state of existence. An argument leads to the creation of two alternate timelines, which need to be stitched back together fast if they are to escape quantum collapse.',
    'S02E02':'Rick and Morty try to save a gas life form while Jerry resides in a daycare made for Jerrys.',
    'S02E03':'Rick gets emotional. Beth and Jerry get into a fight.',
    'S02E04':'The Smith house is locked down after parasites threaten to take over the world by multiplying through flashbacks.',
    'S02E05':'Rick and morty must aid Earth after a giant head disrupts the planet, demanding to see a hit song performed.',
    'S02E06':'Rick is having trouble with his car and they have to fix it by traveling to the microverse.',
    'S02E07':'Rick joins in on some hijinks by transferring his consciousness into teenage "Tiny Rick." Beth and Jerry sort out their relationship.',
    'S02E08':'Jerry is faced with the difficult decision of losing his manhood in order to save an alien leader from imminent death. Meanwhile, Rick, Morty and Summer explore the possibilities of interdimensional television.',
    'S02E09':'Rick and Morty arrive on an alien planet to fix their ship just as the day of the purge begins there, Jerry and Summer work on their father-daughter relationship, but his lack of employment keeps coming up.',
    'S02E10':'The Smith family is invited to the wedding of Rick\'s best friend, Birdperson. Things go south when it\'s discovered that the bride isn\'t who she says she is.',
    'S03E01':'Rick, still in galactic prison, puts an intricate escape plan into action. Back on Earth, which is now under federation control, Morty and Summer have an argument about their grandpa.',
    'S03E02':'With the kids dealing with their parents\' divorce, Rick takes them to a Mad Max-style universe where he tries to steal a green crystal from a group of scavengers.',
    'S03E03':'Rick turns himself into a pickle while Beth, Summer, and Morty go to family therapy.',
    'S03E04':'Rick and Morty are summoned by the Vindicators to stop Worldender but end up in a deathtrap conceived by Drunk Rick.',
    'S03E05':'Rick takes Jerry on a sympathy adventure to a resort where everyone is immortal when there, and Jerry meets some old acquaintances of Rick\'s who want payback.',
    'S03E06':'Following a stressful adventure, Rick and Morty go on a break to a spa where they remove their toxins, which in turn take a form of their own.',
    'S03E07':'Whilst Rick and Morty go off to adventure in Atlantis, we take a look at how the Citadel has rebuilt itself since both Rick and Morty visited.',
    'S03E08':'Rick reveals to Morty his "Morty\'s mind blowers," a collection of memories Morty asked Rick to erase from his mind.',
    'S03E09':'Rick brings Beth to a world he created for her when she was younger while Beth looks for a long-lost childhood friend trapped there for years.',
    'S03E10':'Rick and Morty are called upon by the president to kill a vicious alien in the secret tunnels under the White House.',
    'S04E01':'Rick brings Morty to a planet containing crystals that show whoever is touching them all the ways they may die depending on their choices.',
    'S04E02':'Rick goes to his private bathroom to find that someone else has used it. Jerry creates an app with an unlikely alien and Morty pays the price.',
    'S04E03':'On a treasure-seeking expedition in an alien temple, Rick and Morty discover that a heist expert has snatched the prize from under their noses. Further twists, turns and double-crosses abound.',
    'S04E04':'Morty asks Rick for a dragon and Rick finds a wizard of another dimension who makes a soul bonding contract between Morty and a dragon called Balthromaw. Meanwhile, Jerry meets a talking cat in his bedroom who wants to fly to Florida.',
    'S04E05':'Morty descubre una raza de serpientes espaciales inteligentes después de sufrir una mordida potencialmente letal. Jerry trata de probar que no es completamente incompetente.',
    'S04E06':'An anthology episode that follows Rick and Morty on a train with people who don\'t like Rick. They have to find their way out but they bump into unexpected situations along the way.',
    'S04E07':'Rick, Morty and Summer visit an alien civilisation, where Rick and Morty are controlled by parasites and Summer lives a luxurious lifestyle.',
    'S04E08':'Rick & Morty go on a simple exchange as Rick tells Morty if something goes wrong jump into the same vat of acid as he does.',
    'S04E09':'Rick, Morty, Beth, Summer and Jerry share a galactic adventure.',
    'S04E10':'An adventure with an invisibility belt, but a family that disappears together, must stay together.',
    'S05E01':'Rick invita a cenar a su némesis, el señor Nimbus, hacia quien Beth y Jerry se encuentran inmediatamente atraídos. Morty, que tiene una cita con Jessica esa noche, solo tiene que ocuparse del vino.',
    'S05E02':'The Smiths suspect they\'re being hunted. But who\'s even real?',
    'S05E03':'Morty empieza a salir con Planetina, una joven que es invocada por cuatro personas en el mundo para evitar desastres naturales y la contaminación. Mientras, Rick y Summer van a tres fiestas sin límites en planetas al borde de la extinción.',
    'S05E04':'A Morty se le ocurre la idea de masturbarse con una máquina para extraer semen de caballos. Quando Rick quiere utilizar el semen para crear un arma, pensando que es de caballo, crea monstruos de esperma que amenazan al país.',
    'S05E05':'Summer y Morty roban el auto de Rick para impresionar a un niño nuevo en la escuela. Mientras tanto, Rick y Jerry tienen una noche de chicos del infierno.',
    'S05E06':'In this Thanksgiving episode, Rick and Morty need to get a presidential pardon.',
    'S05E07':'Summer enables Rick\'s addiction to collecting giant combining robots, and the family becomes The Family.',
    'S05E08':'Rick intenta salvar a un querido amigo.',
    'S05E09':'Cansados uno del otro, Rick y Morty buscan un nuevo compañero para sus aventuras.',
    'S05E10':'Como en un anime Rick vive al máximo, hace amigos y acaba con nuevos enemigos.',
};

export default episodeDescriptions;